export const COMMON_ITEMS = [
  { name: 'Blaster Pistol', load: 1 },
  { name: '2nd Blaster Pistol', load: 1 },
  { name: 'Melee Weapon', load: 1 },
  { name: 'Heavy Blaster', load: 2 },
  { name: 'Detonator', load: 1 },
  { name: 'Hacking Tools', load: 1 },
  { name: 'Repair Tools', load: 1 },
  { name: 'Medkit', load: 2 },
  { name: 'Spy Gear', load: 1 },
  { name: 'Illicit Drugs', load: 0 },
  { name: 'Communicator', load: 0 },
  { name: 'Armor', load: 2 },
  { name: 'Spacesuit', load: 2 },
];

export const PLAYBOOK_ITEMS = {
  mechanic: [
    { name: 'Fine Hacking Rig', load: 1 },
    { name: 'Fine Ship Repair Tools', load: 2 },
    { name: 'Small Drone', load: 0 },
    { name: 'Vision-Enhancing Goggles', load: 1 },
    { name: 'Spare Parts', load: 1 },
    { name: 'Genius Pet', load: 0 },
  ],
  pilot: [
    { name: 'Fine Customized Spacesuit', load: 2 },
    { name: 'Fine Small Urbot', load: 2 },
    { name: 'Fine Mechanics Kit', load: 1 },
    { name: 'Grappling Hook', load: 1 },
    { name: 'Guild License', load: 1 },
    { name: 'Victory Cigars', load: 0 },
  ],
  mystic: [
    { name: 'Fine Melee Weapon', load: 2 },
    { name: 'Offerings', load: 1 },
    { name: 'Trappings of Religion', load: 1 },
    { name: 'Outdated Religious Outfit', load: 0 },
    { name: 'Memento of Your Travels', load: 0 },
    { name: 'Precursor Artifact', load: 1 },
  ],
  stitch: [
    { name: 'Fine Medkit', load: 2 },
    { name: 'Fine Bedside Manner', load: 0 },
    { name: 'Fine Clothing', load: 1 },
    { name: 'Recognizable Medic Garb', load: 0 },
    { name: 'Candies and Treats', load: 1 },
    { name: 'Syringes and Applicators', load: 0 },
  ],
};
